# Generated by Django 4.2.26 on 2025-11-20 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_badge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='add_badge.badge')),
            ],
        ),
    ]
