# Generated by Django 4.2.26 on 2025-11-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_badge', '0002_badgerequirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgerequirements',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
